name: CI

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

env:
  CMSIS: CMSIS_5

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: make-action
        uses: Qful/make-action@master
        with:
          release: 10-2020-q4

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: build
        if: matrix.os == 'ubuntu-latest'
        run: |
          make prerequisites
          make stm32f103x8
          make crypter
          make testsuite

      - name: build
        if: matrix.os == 'windows-latest'
        run: |
          make prerequisites
          make stm32f103x8 SHELL=cmd
          make crypter SHELL=cmd SWTOOLS=
          make testsuite SHELL=cmd SWTOOLS=

      - name: build
        if: matrix.os == 'macos-latest'
        run: |
          brew install make
          gmake prerequisites
          gmake stm32f103x8
          gmake crypter
          gmake testsuite

      - name: vector test
        run: |
          build/cipher_test

      - uses: actions/upload-artifact@v2
        with:
          name: sboot_${{ matrix.os }}
          path: build
